spring:
  application:
    name: application

  profiles:
    active: oauth-dev

  config:
    import: optional:configserver:http://localhost:8888

  kafka:
    bootstrap-servers: localhost:29092

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, bus-refresh

  endpoint:
    refresh:
      enabled: true