server:
  port: 8761 #??? ???? ???? ??? ?????? ???? ??

spring:
  application:
    name: discoveryservice #???? ?? ??? ?? ??ID

eureka:
  client: #?? ???? eureka-client? ??? server?? ??? ??
    register-with-eureka: false
    fetch-registry: false
