server:
  port: 8888

spring:
  application:
    name: demo-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hgene2452/Spring_Cloud_Study/tree/main/demo-config
          search-paths: config-file/**
          default-label: main
